# Header
menu:
  Home: /
  Start: /start
  Examples: /examples
  Document: /doc
  News: /archives
  Feedback: /feedback
  About: /about

# Miscellaneous
favicon: /assets/images/avatar.ico
logo: /assets/images/logo.png
bg: /assets/images/bg.png
ICP: 蜀ICP备16028738号-4

button:
  start: 下载 v1.1.2
  more: 历史版本

# Dist
dist:
  release: https://gitee.com/werelone/Easy2D/attach_files/download?i=98208&u=http%3A%2F%2Ffiles.git.oschina.net%2Fgroup1%2FM00%2F02%2F09%2FPaAvDFnbHqKAYJPHACieJVd-PoA392.exe%3Ftoken%3D5e3d0886af68238037a85b9d7292d9aa%26ts%3D1507532456%26attname%3DEasy2D_v1.1.2.exe
  history: https://gitee.com/werelone/Easy2D/releases
  github: https://github.com/Nomango/Easy2D/

# Plugins
plugins:
  leancloud:
    app_id: vlit2JhV3ayuPyc63FSCqqYW-gzGzoHsz
    app_key: lLomVC08AvETTm7wnz2cV3R0