# Header
menu:
  home: /
  download: /download
  history: /history
  start: /start
  tutorial: /tutorial
  examples: /examples
  document: /doc
  news: /archives
  feedback: /feedback
  about: /about

# Dist
dist:
  release: http://easy2d-bucket.oss-cn-hangzhou.aliyuncs.com/release/Easy2D-v2.0.0-beta2.exe
  history: https://gitee.com/werelone/Easy2D/releases
  gitee: https://gitee.com/werelone/Easy2D/
  github: https://github.com/Nomango/Easy2D/

# Index
index:
  subtitle: 快速开发高质量的 2D 小游戏
  button:
    last: v2.0.0-beta2
    more: 历史版本
  examples:
  - name: Flappy Bird
    author: Nomango
    image: /examples/FlappyBird/FlappyBird.png
    description: 像素鸟是曾经超火的一款手机游戏，手残党勿入~
    url: /examples/#FlappyBird
  - name: Smart Clock
    author: Nomango
    image: /examples/SmartClock/SmartClock.png
    description: 一个奇奇怪怪的时钟，感受时间在不知不觉中的流逝。
    url: /examples/#SmartClock
  - name: 推箱子
    author: Nomango
    image: /examples/PushBox/PushBox.png
    description: 经典推箱子，一共有八关，自动保存最佳纪录，音效可关闭。
    url: /examples/#PushBox

# Miscellaneous
local: false
favicon: /assets/images/avatar.ico
logo: /assets/images/logo.png
ICP: 蜀ICP备16028738号-4

# Plugins
plugins:
  leancloud:
    app_id: vlit2JhV3ayuPyc63FSCqqYW-gzGzoHsz
    app_key: lLomVC08AvETTm7wnz2cV3R0